kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: arbeidsgiver-inkludering-kafka-manager
  namespace: arbeidsgiver-inkludering
  labels:
    team: arbeidsgiver-inkludering
spec:
  image: ghcr.io/navikt/kafka-manager/kafka-manager:2.2021.06.08_08.54-87eab24b081e
  port: 8080
  webproxy: true
  ingresses:
    - https://arbeidsgiver-inkludering-kafka-manager.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 729012d4-2e07-43e0-9695-6042955e1269
  kafka:
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON
      value: >
        {
          "topics": [
            {
              "name": "arbeidsgiver-inkludering.rapid",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }