kind: Application
apiVersion: nais.io/v1alpha1
metadata:
    name: toi-kafkamanager
    namespace: toi
    labels:
        team: toi
spec:
    image: ghcr.io/navikt/kafka-manager/kafka-manager:2.2021.12.13_10.49-62142f80d7d3
    port: 8080
    webproxy: true
    ingresses:
        - https://toi-kafkamanager.intern.nav.no
    prometheus:
        enabled: true
        path: /internal/prometheus
    readiness:
        path: /internal/health/readiness
        initialDelay: 20
    liveness:
        path: /internal/health/liveness
        initialDelay: 20
    replicas:
        min: 1
        max: 1 # 1 instance is required since in-memory session management is used
        cpuThresholdPercentage: 75
    resources:
        limits:
            cpu: '1'
            memory: 1024Mi
        requests:
            cpu: 250m
            memory: 512Mi
    azure:
        application:
            enabled: true
            allowAllUsers: false
            tenant: nav.no
            claims:
                groups:
                    - id: 729012d4-2e07-43e0-9695-6042955e1269
    kafka:
        pool: nav-prod
    env:
        - name: APP_CONFIG_JSON
          value: >
              {
                "topics": [
                  {
                    "name": "toi.rapid-1",
                    "location": "AIVEN",
                    "keyDeserializerType": "STRING",
                    "valueDeserializerType": "STRING"
                  },
                  {
                    "name": "toi.rekrutteringsbistand-stilling-1",
                    "location": "AIVEN",
                    "keyDeserializerType": "STRING",
                    "valueDeserializerType": "AVRO"
                  },
                  {
                    "name": "toi.kandidat-3",
                    "location": "AIVEN",
                    "keyDeserializerType": "STRING",
                    "valueDeserializerType": "STRING"
                  },
                  {
                    "name": "toi.sammenstilt-kandidat",
                    "location": "AIVEN",
                    "keyDeserializerType": "STRING",
                    "valueDeserializerType": "STRING"
                  },
                  {
                    "name": "toi.tillretteleggingsbehov-1",
                    "location": "AIVEN",
                    "keyDeserializerType": "STRING",
                    "valueDeserializerType": "STRING"
                  }
                ]
              }
