name: Deploy kafkamanager to dev

on:
  push:
    branches:
      - main

jobs:
  deploy-kafkamanager-to-dev:
    name: Deploy kafkamanager to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais.yaml